### ISSUE TITLE
Mining Googles

### ISSUE THREAD

**Issue by Wurmatron** [Wurmatron/Project-Wish#15]
Tier's determine range
Kinda like spector arrow

**Comment by troykoffeman** [comment]
upgrade table maybe that adds range/identification/toggle maybe which ore you want to see? kinda like blacklist siderite/rutile or whitelist things

**Comment by troykoffeman** [comment]
another 2 upgrades, 
adding light emission from the goggles as an upgrade kinda like holding a torch in SOTA.
upgrade B
add prospecting pick long range into goggles, right click with a pick axe to prospect. maybe configurable by ranges the player can set, to a max amount. kinda like the digital miner's digging criteria

**Comment by troykoffeman** [comment]
if its gonna be a helmet, maybe fortification upgrades too, think thorns/extra plating. even maybe the mob camouflage glowstick

**Comment by troykoffeman** [comment]
mode/new item

Fluid Searching Mode.
Cave searching mode.
ender Structure/structure mode?

**Comment by troykoffeman** [comment]
Monster glasses. searches types of monsters
